short_reads_1:
    none
short_reads_2:
    none
n_cores:
    8
max_memory:
    32
genome_dir:
    none
ref:
    none
gff:
    none
fasta_extension:
    fna
output:
    none
conda_prefix:
     /lustre/work-lustre/microbiome/users/sternesp/conda/envs/
human_db:
    none
silva_db:
    none
trimmomatic:
    MINLEN:60 ILLUMINACLIP:/-SE.fa:2:30:10 SLIDINGWINDOW:4:20 MINLEN:50
sequencer_source:
    NexteraPE
kingdom:
    none
workflow:
    pipe
other_db:
    none
