short_reads_1:
    none
short_reads_2:
    none
n_cores:
    8
max_memory:
    64
genome_dir:
    none
ref:
    none
gff:
    none
fasta_extension:
    fna
output:
    none
sequencer_source:
    TruSeq3-PE
kingdom:
    none
workflow:
    count
other_db:
    none
skip_qc:
    false
min_read_aligned_percent:
    0.90
min_read_percent_identity:
    0.95
gDNA:
    1

